/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test.gradle.command.action;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
